### ISSUE TITLE
Typings with strict tsconfig settings

### ISSUE THREAD

**Issue by j-walker23** [martinsik/rxjs-extra#1]
Hey. Sorry to bug you with just typings but I am extremely interested in using your cool `takeWhileInclusive` operator.

I have most of the `strict` tsconfig settings turned on unfortunately and angular/typescript is giving me a `The 'this' context of type 'void' is not assignable to method's 'this' of type 'Observable<{}>'`.

I am brand new to rxjs so it's going to take me a little while to figure out how to type it correctly. But if I get it figured out I'll post a PR. Figured I'd post this in case it's an easy fix for you.

Thanks for this cool lib of extras. Shit seems really handy!

**Edit:**
Copying from the `rxjs` source for `takeWhile` might be a fix.

```
export function takeWhileInclusive<T>(predicate: (value: T, index: number) => boolean): MonoTypeOperatorFunction<T> {
  return (source: Observable<T>) => source.lift(new TakeWhileInclusiveOperator(predicate))
}
```

**Comment by martinsik** [comment]
Hey, I'm actually working on a large update to support pipable operators from RxJS 5.5 so I'll have a look at this after I release the new version.

**Comment by martinsik** [comment]
Ok, now I promise I really am...

**Comment by martinsik** [comment]
`takeWhile` now takes an optional `inclusive` parameter so it's better to use the official one. https://rxjs.dev/api/operators/takeWhile

**Comment by j-walker23** [comment]
Awesome, thanks @martinsik!
