### ISSUE TITLE
Does not package correctly on Windows

### ISSUE THREAD

**Issue by codemile** [martinsik/rxjs-extra#22]
I was trying to build the npm package on Windows 10 using Git bash by doing the following:

```sh
./tool/make-package.sh
```

The output structure of `dist/package` was like this

```
./
../
CHANGELOG.md
LICENSE
README.md
bundles/
cjs/
package.json
src/
typings/
```

The `cjs` and `typings` folders were copied to a *subfolder* instead of being copied directly to *package*. In order to fix this I had to change the following lines in the `make-package.sh` file.

```bash
cp -R dist/cjs/* dist/package
cp -R dist/typings/* dist/package
```

This should probably be changed in the repo.

**Comment by martinsik** [comment]
Hey @codemile, you were right, it was broken on Windows.
