### ISSUE TITLE
Make PersistenSubject default to BehaviorSubject

### ISSUE THREAD

**Issue by Mateiadrielrafael** [martinsik/rxjs-extra#23]
Im using this in a ssr enviroment and i have to always do: 
```ts
process.browser ? new PersistenSubject(...) : new BehaviorSubject(...)
```

Would it be a good idea to default to in memory storage if localstorage doesnt exist?

Btw: this is one of the coolest libs i've ever used:)  Keep it up!

**Comment by martinsik** [comment]
Hmm..., I think you're right. `localStorage` might not exist so it shouldn't be the default storage. I'll fix this asap.

**Comment by Mateiadrielrafael** [comment]
Thanks a lot!

**Comment by Mateiadrielrafael** [comment]
#24 should fix it
